package menuscene

import (
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"runtime"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/huh"
	"github.com/charmbracelet/lipgloss"
	"github.com/gonebot-dev/gonebuilder-tui/app/base"
	"github.com/gonebot-dev/gonebuilder-tui/app/router"
	t "github.com/gonebot-dev/gonebuilder-tui/app/utils/translator"
)

func browsers() (cmds []string) {
	cmds = make([]string, 0)
	if userBrowser := os.Getenv("BROWSER"); userBrowser != "" {
		cmds = append(cmds, userBrowser)
	}
	switch runtime.GOOS {
	case "darwin":
		cmds = append(cmds, "/usr/bin/open")
	case "windows":
		cmds = append(cmds, "cmd /c start")
	default:
		// Commands opening browsers are prioritized over xdg-open, so browser()
		// command can be used on linux to open the .svg file generated by the -web
		// command (the .svg file includes embedded javascript so is best viewed in
		// a browser).
		cmds = append(cmds, []string{"chrome", "google-chrome", "chromium", "firefox", "sensible-browser"}...)
		if os.Getenv("DISPLAY") != "" {
			// xdg-open is only for use in a desktop environment.
			cmds = append(cmds, "xdg-open")
		}
	}
	return
}

// open browser with url
func openBrowser(targetUrl string) (err error) {
	// Construct URL.
	u, _ := url.Parse(targetUrl)

	for _, b := range browsers() {
		args := strings.Split(b, " ")
		if len(args) == 0 {
			continue
		}
		viewer := exec.Command(args[0], append(args[1:], u.String())...)
		viewer.Stderr = os.Stderr
		if err = viewer.Start(); err == nil {
			return
		}
	}
	// No visualizer succeeded, so just print URL.
	fmt.Println(u.String())
	return
}

type menuScene struct {
	router.Scene
	form *huh.Form
}

func (ms menuScene) Name() string {
	return "MenuScene"
}

func (ms menuScene) Init() tea.Cmd {
	return ms.form.Init()
}

func (ms menuScene) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.Type {
		case tea.KeyCtrlC:
			return ms, tea.Quit
		case tea.KeyCtrlF:
			base.Lang = base.IfElse(base.Lang == "en", "zh", "en")
		}
	case tea.WindowSizeMsg:
		base.WindowHeight = msg.Height
		base.WindowWidth = msg.Width
	}

	var cmds []tea.Cmd
	form, cmd := ms.form.Update(msg)
	if f, ok := form.(*huh.Form); ok {
		cmds = append(cmds, cmd)
		ms.form = f
	}

	if ms.form.State == huh.StateCompleted {
		base.SelectedAction = ms.form.GetInt("action")
		if os.Getenv("DEBUG") == "true" {
			return ms, tea.Quit
		}
		// TODO: Add jump scenes
		if base.SelectedAction == base.NewBot {
			cmds = append(cmds, router.NextScene("NewBotScene"))
		} else if base.SelectedAction == base.Adapters {
			openBrowser("https://github.com/gonebot-dev/gonerepo/tree/main/packages/adapters")
			return ms, tea.Quit
		} else if base.SelectedAction == base.Plugins {
			openBrowser("https://github.com/gonebot-dev/gonerepo/tree/main/packages/plugins")
			return ms, tea.Quit
		} else {
			return ms, tea.Quit
		}
	}

	return ms, tea.Batch(cmds...)
}

func (ms menuScene) View() string {
	base.Header = base.Header.Width(base.WindowWidth)
	base.Footer = base.Footer.Width(base.WindowWidth)
	base.Content = base.Content.Width(base.WindowWidth).
		Height(base.WindowHeight - 2)
	base.FormStyle = base.FormStyle.Width(min(base.WindowWidth-8, 64))

	return base.MainFrame.Render(fmt.Sprintf(
		"%s\n%s\n%s",
		base.Header.Render("GoneBuilder - Copyright © 2024 gonebot-dev"),
		base.Content.Render(
			base.FormStyle.Render(ms.form.WithHeight(10).View()),
		),
		base.Footer.Render(
			fmt.Sprintf("%s%s%s%s",
				base.FooterTitle.Render(t.Translate("Exit")),
				base.FooterText.Render("Ctrl+C"),
				base.FooterTitle.Render(t.Translate("让我们说中文")),
				base.FooterText.Render("Ctrl+F"),
			),
		),
	))
}

var MenuScene = menuScene{
	form: huh.NewForm(
		huh.NewGroup(
			huh.NewSelect[int]().
				Key("action").
				TitleFunc(func() string {
					return lipgloss.NewStyle().
						Bold(true).
						Render(t.Translate("What can I do for you?"))
				}, &base.Lang).
				DescriptionFunc(func() string { return t.Translate("Select an option to continue...") + "\n" }, &base.Lang).
				OptionsFunc(
					func() []huh.Option[int] {
						return []huh.Option[int]{
							huh.NewOption(t.Translate("Create a new gonebot."), base.NewBot),
							huh.NewOption(t.Translate("Modify an existing gonebot."), base.EditBot),
							huh.NewOption(t.Translate("Manage .env configurations."), base.DotEnv),
							huh.NewOption(t.Translate("Explore plugin repository.(Desktop required)"), base.Plugins),
							huh.NewOption(t.Translate("Explore adapter repository.(Desktop required)"), base.Adapters),
							huh.NewOption(t.Translate("Exit the application."), base.ExitApp),
						}
					},
					&base.Lang,
				),
		),
	),
}
